# Generated by Django 5.0.2 on 2024-05-28 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixd', models.CharField(max_length=250)),
                ('transaction_id', models.CharField(max_length=250)),
                ('total_amount', models.IntegerField()),
                ('mobile', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=250)),
                ('user_email', models.EmailField(max_length=254)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_id', models.CharField(max_length=100)),
                ('purchase_order_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
