# Generated by Django 5.0.2 on 2024-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_useraccount_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Admin', 'A'), ('User', 'U'), ('Staff', 'S')], default='User', max_length=10),
        ),
    ]
