# Generated by Django 5.0.2 on 2024-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Admin', 'A'), ('Customer', 'C'), ('Staff', 'S')], default='User', max_length=10),
        ),
    ]
