# Generated by Django 5.0.2 on 2024-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'A'), ('CUSTOMER', 'C'), ('STAFF', 'S')], default='CUSTOMER', max_length=10),
        ),
    ]
